language: R
cache: packages

warnings_are_errors: true

r_packages:
  - covr
  - lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - Rscript rsconnect.R

after_failure:
- find *Rcheck -name '*fail' -print -exec cat '{}' \;
